# Generated by Django 5.1.2 on 2024-11-11 05:29

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('userID', models.CharField(max_length=100, unique=True)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userName', models.CharField(max_length=100)),
                ('userDetail', models.TextField(blank=True, null=True)),
                ('userRole', models.CharField(blank=True, max_length=50, null=True)),
                ('userPriority', models.CharField(blank=True, max_length=50, null=True)),
                ('approve', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='user_num')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Openstack username')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 11, 14, 29, 57, 609249), verbose_name='생성된 시간')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제된 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 날짜')),
                ('password', models.CharField(max_length=150, verbose_name='오픈스택 패스워드')),
                ('email', models.EmailField(max_length=300, verbose_name='이메일')),
            ],
            options={
                'verbose_name_plural': 'DMSLAB Openstack',
                'db_table': 'project_users',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='resource_num')),
                ('network', models.CharField(max_length=100, unique=True, verbose_name='Network Name')),
                ('subnet', models.CharField(max_length=100, verbose_name='Subnet Name')),
                ('CIDR', models.CharField(max_length=100, verbose_name='CIDR')),
                ('keypair', models.CharField(max_length=100, null=True, verbose_name='key-pair')),
                ('gateway', models.CharField(max_length=100, null=True, verbose_name='Gateway_ip')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 11, 14, 29, 57, 611249), verbose_name='생성된 시간')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제된 시간')),
            ],
            options={
                'verbose_name_plural': 'User Resources',
                'db_table': 'resources',
            },
        ),
    ]
