# Generated by Django 5.1.2 on 2024-11-03 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack3', '0002_alter_user_options_user_created_at_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='resource_num')),
                ('network', models.CharField(max_length=100, unique=True, verbose_name='Network Name')),
                ('subnet', models.CharField(max_length=100, verbose_name='Subnet Name')),
                ('CIDR', models.CharField(max_length=100, verbose_name='CIDR')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 3, 15, 38, 54, 76736), verbose_name='생성된 시간')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제된 시간')),
            ],
            options={
                'verbose_name_plural': 'User Resources',
                'db_table': 'resources',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 15, 38, 54, 33621), verbose_name='생성된 시간'),
        ),
    ]
