# Generated by Django 5.1.2 on 2024-11-17 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack3', '0003_resources_requested_by_resources_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 15, 12, 43, 343517), verbose_name='생성된 시간'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 15, 12, 43, 343517), verbose_name='생성된 시간'),
        ),
    ]
