# Generated by Django 5.1.2 on 2024-11-19 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack3', '0005_alter_projectuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Request ID')),
                ('request_type', models.CharField(choices=[('public_ip', 'Public IP'), ('vpn_ip', 'VPN IP')], max_length=20, verbose_name='Request Type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Assigned IP Address')),
                ('server_name', models.CharField(max_length=100, verbose_name='Associated Server Name')),
                ('network_name', models.CharField(max_length=100, verbose_name='Network Name')),
                ('requested_by', models.CharField(max_length=100, verbose_name='Requested By')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Request Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Public IP Requests',
                'db_table': 'public_ip_requests',
            },
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 19, 7, 35, 643334), verbose_name='생성된 시간'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 19, 7, 35, 643334), verbose_name='생성된 시간'),
        ),
    ]
