# Generated by Django 5.1.2 on 2024-11-19 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack3', '0006_iprequest_alter_projectuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iprequest',
            options={'verbose_name_plural': 'IP Requests'},
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 19, 14, 6, 448106), verbose_name='생성된 시간'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 19, 14, 6, 451745), verbose_name='생성된 시간'),
        ),
        migrations.AlterModelTable(
            name='iprequest',
            table='ip_requests',
        ),
    ]
